SELECT	-- nombreCorto = (SELECT dep_nombrecto from [ControlAplicaciones].[dbo].[cat_departamentos] where  dep_iddepartamento = DR.idDepartamento),					rap_idempresa = R.idEmpresa,	rap_idsucursal = DR.idSucursal,	rap_iddepartamento = CASE R.idEmpresa 							WHEN 4 THEN (											CASE (SELECT dep_nombrecto from [ControlAplicaciones].[dbo].[cat_departamentos] where  dep_iddepartamento = DR.idDepartamento)												WHEN 'OT' THEN (																	CASE DR.idSucursal																		WHEN 6 THEN 26																		WHEN 7 THEN 31																		WHEN 8 THEN 36																	END																)												ELSE CONVERT(VARCHAR(18),DR.idDepartamento)											END										)							ELSE CONVERT(VARCHAR(18),DR.idDepartamento)						END,	rap_idpersona = DR.idCliente,	rap_cobrador = 'MMK',	rap_moneda = 'PE',	rap_tipocambio = 1,	-- rap_referencia = ltrim(SAN.concepto) COLLATE SQL_Latin1_General_CP1_CI_AS,	rap_referencia = CASE  -- Unidades Nuevas y Seminuevas						WHEN (SELECT dep_nombrecto from [ControlAplicaciones].[dbo].[cat_departamentos] where  dep_iddepartamento = DR.idDepartamento) IN ('UN','US')						 THEN  (									CASE WHEN ( SELECT CONVERT(VARCHAR(18),ucu_idcotizacion) FROM cuentasporcobrar.DBO.UNI_COTIZACIONUNIVERSALUNIDADES WHERE ucn_idFactura COLLATE Modern_Spanish_CS_AS = DR.documento ) IS NOT NULL
										 THEN (SELECT ucu_foliocotizacion FROM cuentasporcobrar.DBO.UNI_COTIZACIONUNIVERSAL WHERE ucu_idcotizacion = (SELECT ucu_idcotizacion FROM cuentasporcobrar.DBO.UNI_COTIZACIONUNIVERSALUNIDADES WHERE ucn_idFactura COLLATE Modern_Spanish_CS_AS = DR.documento)) COLLATE Modern_Spanish_CS_AS
										ELSE DR.documento
									END								)						ELSE DR.documento				   END,				   	-- rap_iddocto =  dr.documento,		rap_iddocto = CASE  -- Unidades Nuevas y Seminuevas						WHEN (SELECT dep_nombrecto from [ControlAplicaciones].[dbo].[cat_departamentos] where  dep_iddepartamento = DR.idDepartamento) IN ('UN','US')						 THEN  (									CASE WHEN ( SELECT ucu_idcotizacion FROM cuentasporcobrar.DBO.UNI_COTIZACIONUNIVERSALUNIDADES WHERE ucn_idFactura COLLATE Modern_Spanish_CS_AS = DR.documento ) IS NOT NULL
										 THEN DR.documento
										ELSE ''
									END								)						ELSE ''				   END,		-- rap_cotped = ''	rap_cotped = CASE  -- Unidades Nuevas y Seminuevas						WHEN (SELECT dep_nombrecto from [ControlAplicaciones].[dbo].[cat_departamentos] where  dep_iddepartamento = DR.idDepartamento) IN ('UN','US')						 THEN  (									CASE WHEN ( SELECT ucu_idcotizacion FROM cuentasporcobrar.DBO.UNI_COTIZACIONUNIVERSALUNIDADES WHERE ucn_idFactura COLLATE Modern_Spanish_CS_AS = DR.documento ) IS NOT NULL
										 THEN 'COTIZACION UNIVERSAL'
										ELSE ''
									END								)						ELSE ''				   END,		rap_consecutivo = (SELECT CCP_CONSCARTERA FROM [192.168.20.31].[GAZM_Abasto].[dbo].VIS_CONCAR01 WHERE CCP_TIPODOCTO = 'FAC' AND CCP_IDDOCTO COLLATE Modern_Spanish_CS_AS= DR.documento AND CCP_IDPERSONA = DR.IdCliente),	-- rap_consecutivo = 400000,	rap_importe = convert(decimal,SAN.importe),	rap_formapago = (select top 1 co.CodigoBPRO  from Santander S inner join  CodigoIdentificacion co on co.CodigoBanco = S.clacon where S.concepto =  R.referencia),	rap_numctabanc = SAN.noCuenta,	rap_fecha = GETDATE(),	rap_idusuari = (SELECT usu_idusuario FROM ControlAplicaciones..cat_usuarios WHERE usu_nombreusu = 'GMI'),	rap_idstatus = '1',	rap_banco = C.IdBanco_bpro,	rap_referenciabancaria = R.referencia,	rap_anno = (SELECT Vcc_Anno FROM [192.168.20.31].[GAZM_Abasto].[dbo].VIS_CONCAR01 WHERE CCP_TIPODOCTO = 'FAC' AND CCP_IDDOCTO COLLATE Modern_Spanish_CS_AS= DR.documento AND CCP_IDPERSONA = DR.IdCliente), 	RAP_AplicaPago = convert(numeric(18,2),SAN.importe),	RAP_NumDeposito = 1 FROM Referencia R INNER JOIN Santander SAN ON R.Referencia = SAN.conceptoINNER JOIN Centralizacionv2..DIG_CAT_BASES_BPRO BP ON R.idEmpresa = BP.emp_idempresa INNER JOIN Rel_BancoCobro C ON R.idEmpresa = C.emp_idempresaINNER JOIN DetalleReferencia DR ON  DR.idReferencia = R.idReferencia AND DR.idSucursal = BP.suc_idsucursalWHERE SAN.estatusRevision = 2 	   AND SAN.signo = '+' 	   AND DR.idTipoDocumento = 1	   AND C.IdBanco = 3	   AND SAN.idSantander = 663017